name: docker-centos7-slurm
on:
  push:
    tags:
      - '*'
  # DEBUG ONLY
  pull_request: {}
jobs:
  Build-Image:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: giovtorres/docker-centos7-slurm:${GITHUB_REF#refs/tags/}"
